// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: taskModel.proto

package service

import (
	fmt "fmt"
	math "math"

	proto "google.golang.org/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
