// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: taskService.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       int64                  `protobuf:"varint,6,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Status        int64                  `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty"`
	Start         uint32                 `protobuf:"varint,8,opt,name=Start,proto3" json:"Start,omitempty"`
	Limit         uint32                 `protobuf:"varint,9,opt,name=Limit,proto3" json:"Limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_taskService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_taskService_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TaskRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskRequest) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TaskRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TaskListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskList      []*TaskModel           `protobuf:"bytes,1,rep,name=TaskList,proto3" json:"TaskList,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskListResponse) Reset() {
	*x = TaskListResponse{}
	mi := &file_taskService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListResponse) ProtoMessage() {}

func (x *TaskListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListResponse.ProtoReflect.Descriptor instead.
func (*TaskListResponse) Descriptor() ([]byte, []int) {
	return file_taskService_proto_rawDescGZIP(), []int{1}
}

func (x *TaskListResponse) GetTaskList() []*TaskModel {
	if x != nil {
		return x.TaskList
	}
	return nil
}

func (x *TaskListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TaskDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskDetail    *TaskModel             `protobuf:"bytes,1,opt,name=TaskDetail,proto3" json:"TaskDetail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDetailResponse) Reset() {
	*x = TaskDetailResponse{}
	mi := &file_taskService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetailResponse) ProtoMessage() {}

func (x *TaskDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetailResponse.ProtoReflect.Descriptor instead.
func (*TaskDetailResponse) Descriptor() ([]byte, []int) {
	return file_taskService_proto_rawDescGZIP(), []int{2}
}

func (x *TaskDetailResponse) GetTaskDetail() *TaskModel {
	if x != nil {
		return x.TaskDetail
	}
	return nil
}

var File_taskService_proto protoreflect.FileDescriptor

const file_taskService_proto_rawDesc = "" +
	"\n" +
	"\x11taskService.proto\x12\aservice\x1a\x0ftaskModel.proto\"\xdb\x01\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x10\n" +
	"\x03Uid\x18\x02 \x01(\x04R\x03Uid\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContent\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aEndTime\x18\x06 \x01(\x03R\aEndTime\x12\x16\n" +
	"\x06Status\x18\a \x01(\x03R\x06Status\x12\x14\n" +
	"\x05Start\x18\b \x01(\rR\x05Start\x12\x14\n" +
	"\x05Limit\x18\t \x01(\rR\x05Limit\"X\n" +
	"\x10TaskListResponse\x12.\n" +
	"\bTaskList\x18\x01 \x03(\v2\x12.service.TaskModelR\bTaskList\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\rR\x05Count\"H\n" +
	"\x12TaskDetailResponse\x122\n" +
	"\n" +
	"TaskDetail\x18\x01 \x01(\v2\x12.service.TaskModelR\n" +
	"TaskDetail2\x8e\x02\n" +
	"\vTaskService\x12?\n" +
	"\n" +
	"CreateTask\x12\x14.service.TaskRequest\x1a\x1b.service.TaskDetailResponse\x12?\n" +
	"\fGetTasksList\x12\x14.service.TaskRequest\x1a\x19.service.TaskListResponse\x12<\n" +
	"\aGetTask\x12\x14.service.TaskRequest\x1a\x1b.service.TaskDetailResponse\x12?\n" +
	"\n" +
	"UpdateTask\x12\x14.service.TaskRequest\x1a\x1b.service.TaskDetailResponseB\vZ\t./;protosb\x06proto3"

var (
	file_taskService_proto_rawDescOnce sync.Once
	file_taskService_proto_rawDescData []byte
)

func file_taskService_proto_rawDescGZIP() []byte {
	file_taskService_proto_rawDescOnce.Do(func() {
		file_taskService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskService_proto_rawDesc), len(file_taskService_proto_rawDesc)))
	})
	return file_taskService_proto_rawDescData
}

var file_taskService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_taskService_proto_goTypes = []any{
	(*TaskRequest)(nil),        // 0: service.TaskRequest
	(*TaskListResponse)(nil),   // 1: service.TaskListResponse
	(*TaskDetailResponse)(nil), // 2: service.TaskDetailResponse
	(*TaskModel)(nil),          // 3: service.TaskModel
}
var file_taskService_proto_depIdxs = []int32{
	3, // 0: service.TaskListResponse.TaskList:type_name -> service.TaskModel
	3, // 1: service.TaskDetailResponse.TaskDetail:type_name -> service.TaskModel
	0, // 2: service.TaskService.CreateTask:input_type -> service.TaskRequest
	0, // 3: service.TaskService.GetTasksList:input_type -> service.TaskRequest
	0, // 4: service.TaskService.GetTask:input_type -> service.TaskRequest
	0, // 5: service.TaskService.UpdateTask:input_type -> service.TaskRequest
	2, // 6: service.TaskService.CreateTask:output_type -> service.TaskDetailResponse
	1, // 7: service.TaskService.GetTasksList:output_type -> service.TaskListResponse
	2, // 8: service.TaskService.GetTask:output_type -> service.TaskDetailResponse
	2, // 9: service.TaskService.UpdateTask:output_type -> service.TaskDetailResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_taskService_proto_init() }
func file_taskService_proto_init() {
	if File_taskService_proto != nil {
		return
	}
	file_taskModel_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskService_proto_rawDesc), len(file_taskService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskService_proto_goTypes,
		DependencyIndexes: file_taskService_proto_depIdxs,
		MessageInfos:      file_taskService_proto_msgTypes,
	}.Build()
	File_taskService_proto = out.File
	file_taskService_proto_goTypes = nil
	file_taskService_proto_depIdxs = nil
}
