// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: userModels.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint32                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,5,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserModel) Reset() {
	*x = UserModel{}
	mi := &file_userModels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModel) ProtoMessage() {}

func (x *UserModel) ProtoReflect() protoreflect.Message {
	mi := &file_userModels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModel.ProtoReflect.Descriptor instead.
func (*UserModel) Descriptor() ([]byte, []int) {
	return file_userModels_proto_rawDescGZIP(), []int{0}
}

func (x *UserModel) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UserModel) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserModel) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserModel) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UserModel) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

var File_userModels_proto protoreflect.FileDescriptor

const file_userModels_proto_rawDesc = "" +
	"\n" +
	"\x10userModels.proto\x12\aservice\"\x91\x01\n" +
	"\tUserModel\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\rR\x02ID\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x1c\n" +
	"\tCreatedAt\x18\x03 \x01(\x03R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\x04 \x01(\x03R\tUpdatedAt\x12\x1c\n" +
	"\tDeletedAt\x18\x05 \x01(\x03R\tDeletedAtB\vZ\t./;protosb\x06proto3"

var (
	file_userModels_proto_rawDescOnce sync.Once
	file_userModels_proto_rawDescData []byte
)

func file_userModels_proto_rawDescGZIP() []byte {
	file_userModels_proto_rawDescOnce.Do(func() {
		file_userModels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userModels_proto_rawDesc), len(file_userModels_proto_rawDesc)))
	})
	return file_userModels_proto_rawDescData
}

var file_userModels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_userModels_proto_goTypes = []any{
	(*UserModel)(nil), // 0: service.UserModel
}
var file_userModels_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userModels_proto_init() }
func file_userModels_proto_init() {
	if File_userModels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userModels_proto_rawDesc), len(file_userModels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userModels_proto_goTypes,
		DependencyIndexes: file_userModels_proto_depIdxs,
		MessageInfos:      file_userModels_proto_msgTypes,
	}.Build()
	File_userModels_proto = out.File
	file_userModels_proto_goTypes = nil
	file_userModels_proto_depIdxs = nil
}
