// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: userService.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserName        string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	PassWord        string                 `protobuf:"bytes,2,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	PassWordConfirm string                 `protobuf:"bytes,3,opt,name=PassWordConfirm,proto3" json:"PassWordConfirm,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_userService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_userService_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserRequest) GetPassWord() string {
	if x != nil {
		return x.PassWord
	}
	return ""
}

func (x *UserRequest) GetPassWordConfirm() string {
	if x != nil {
		return x.PassWordConfirm
	}
	return ""
}

type UserDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserDetail    *UserModel             `protobuf:"bytes,1,opt,name=UserDetail,proto3" json:"UserDetail,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailResponse) Reset() {
	*x = UserDetailResponse{}
	mi := &file_userService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailResponse) ProtoMessage() {}

func (x *UserDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailResponse.ProtoReflect.Descriptor instead.
func (*UserDetailResponse) Descriptor() ([]byte, []int) {
	return file_userService_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetailResponse) GetUserDetail() *UserModel {
	if x != nil {
		return x.UserDetail
	}
	return nil
}

func (x *UserDetailResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_userService_proto protoreflect.FileDescriptor

const file_userService_proto_rawDesc = "" +
	"\n" +
	"\x11userService.proto\x12\aservice\x1a\x10userModels.proto\"o\n" +
	"\vUserRequest\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x1a\n" +
	"\bPassWord\x18\x02 \x01(\tR\bPassWord\x12(\n" +
	"\x0fPassWordConfirm\x18\x03 \x01(\tR\x0fPassWordConfirm\"\\\n" +
	"\x12UserDetailResponse\x122\n" +
	"\n" +
	"UserDetail\x18\x01 \x01(\v2\x12.service.UserModelR\n" +
	"UserDetail\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\rR\x04Code2\x90\x01\n" +
	"\vUserService\x12>\n" +
	"\tUserLogin\x12\x14.service.UserRequest\x1a\x1b.service.UserDetailResponse\x12A\n" +
	"\fUserRegister\x12\x14.service.UserRequest\x1a\x1b.service.UserDetailResponseB\vZ\t./;protosb\x06proto3"

var (
	file_userService_proto_rawDescOnce sync.Once
	file_userService_proto_rawDescData []byte
)

func file_userService_proto_rawDescGZIP() []byte {
	file_userService_proto_rawDescOnce.Do(func() {
		file_userService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userService_proto_rawDesc), len(file_userService_proto_rawDesc)))
	})
	return file_userService_proto_rawDescData
}

var file_userService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_userService_proto_goTypes = []any{
	(*UserRequest)(nil),        // 0: service.UserRequest
	(*UserDetailResponse)(nil), // 1: service.UserDetailResponse
	(*UserModel)(nil),          // 2: service.UserModel
}
var file_userService_proto_depIdxs = []int32{
	2, // 0: service.UserDetailResponse.UserDetail:type_name -> service.UserModel
	0, // 1: service.UserService.UserLogin:input_type -> service.UserRequest
	0, // 2: service.UserService.UserRegister:input_type -> service.UserRequest
	1, // 3: service.UserService.UserLogin:output_type -> service.UserDetailResponse
	1, // 4: service.UserService.UserRegister:output_type -> service.UserDetailResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_userService_proto_init() }
func file_userService_proto_init() {
	if File_userService_proto != nil {
		return
	}
	file_userModels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userService_proto_rawDesc), len(file_userService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userService_proto_goTypes,
		DependencyIndexes: file_userService_proto_depIdxs,
		MessageInfos:      file_userService_proto_msgTypes,
	}.Build()
	File_userService_proto = out.File
	file_userService_proto_goTypes = nil
	file_userService_proto_depIdxs = nil
}
